[package]
name = "reverse-proxy"
version = "0.1.0"
edition = "2021"
author = "Tarun Jaiswal <tarunjais28@gmail.com>"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
